# Generated by Django 3.2 on 2024-03-11 09:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_auto_20240311_1024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='cooking_time',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(limit_value=1)], verbose_name='Время приготовления (в минутах)'),
        ),
    ]
