# Generated by Django 3.2 on 2024-03-16 15:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20240307_1617'),
    ]

    operations = [
        migrations.AlterField(
            model_name='following',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follower', to=settings.AUTH_USER_MODEL, verbose_name='Автор'),
        ),
    ]
